### ISSUE TITLE
Date Format in Generate Members reports

### ISSUE THREAD

**Issue by hartnickaus** [NomisNostab/Topo-Blazor#1]
The date format of all dates in the PDF and xls formats are in mm/dd/yyyy rather than dd/mm/yyyy.
This is both "Patrol List" and "Member List"

**Comment by NomisNostab** [comment]
Thanks for that.
Didn't take you long to find this. What do you think of it?

**Comment by hartnickaus** [comment]
Hi James, it seems all dates on reports are in US format rather AU format - so maybe a general setting somewhere.
I do like the layout and think the design is awesome. Happy to review each part as they keep coming out.

**Comment by NomisNostab** [comment]
Updated Azure function to en-AU culture
