### ISSUE TITLE
Glitching functionality for Unit leaders (Youth)

### ISSUE THREAD

**Issue by MrNO13** [NomisNostab/Topo-Blazor#112]
Topo is not working for YOUTH unit leaders, It opens and signs in fine, loads all the tabs on the left and then they all disappear, I can then only view my own progress in logbook, additional awards, and personal progress.

**Comment by MrNO13** [comment]
It appears this is a similar issue that Brendan Wilson had, posted in the support leader access issue on Dec 27, 2023

**Comment by NomisNostab** [comment]
Hi,
Can you capture a log for me so I can see what type of user Terrain has you as.
https://github.com/NomisNostab/Topo-Blazor/wiki/Debug-Logs
PM me on Facebook to get my email address and send there. Don't send here.
Simon

**Comment by NomisNostab** [comment]
Included in Version 1.49
