### ISSUE TITLE
Bad gateway error when trying to produce wallchart?

### ISSUE THREAD

**Issue by wilsteady** [NomisNostab/Topo-Blazor#122]
I've got no idea how to explain this one. Happens regardless of Group/Unit selected when trying to run the WallChart report. Other reports appear to be working fine without any issues.
![image](https://github.com/NomisNostab/Topo-Blazor/assets/12633684/a7093dba-dec6-48e5-9ca0-966c6c8ba23b)

**Comment by wvanduin** [comment]
I have this issue as well.
Happens elsewhere as well.

**Comment by NomisNostab** [comment]
Hi,
The call to terrain to get the group life details can sometimes take a long time and the call times out (I think).
Try doing the Group life for the unit in terrain first and when it loads you should be OK in Topo.
I will try to look into catching the timeout, but it hard to catch.

**Comment by NomisNostab** [comment]
Resolved in Version v1.50
