### ISSUE TITLE
Feature Request: Wallchart split by Patrol

### ISSUE THREAD

**Issue by wilsteady** [NomisNostab/Topo-Blazor#123]
Any chance of adding a checkbox to print the Wallchart report of the whole Unit sorted by Patrol? Something like this? 
![image](https://github.com/NomisNostab/Topo-Blazor/assets/12633684/89d6e0c5-6e31-427d-a8b4-2b0889b29525)

**Comment by NomisNostab** [comment]
Would a page break per patrol work?
See #33  (Wallchart by patrol)

**Comment by NomisNostab** [comment]
Done as part of [Issue-33](https://github.com/NomisNostab/Topo-Blazor/issues/33)
