### ISSUE TITLE
Term Programme Times Adjusted

### ISSUE THREAD

**Issue by hartnickaus** [NomisNostab/Topo-Blazor#127]
It seems that when producing a term programme for future dates, If I am in AEDT and they aren't it calculates the time incorrectly

this is with computer date/time set as Melbourne

![image](https://github.com/NomisNostab/Topo-Blazor/assets/30915527/4ec87d94-6228-4007-8de3-749262d394c8)

this is with computer date/time set as Brisbane

![image](https://github.com/NomisNostab/Topo-Blazor/assets/30915527/6bc6bf7a-ba6a-4380-961b-485d145e4211)

**Comment by NomisNostab** [comment]
Hi Nicholas,

It is related to the change back from Daylight Savings, the service is reporting the time as we would see it now and subtracting the offset, that is why Brisbane is OK.
These differences will go away after the switch back, so you will have to the report once summer time ends.
I will look how I can fix this issue.
Simon

**Comment by NomisNostab** [comment]
Hi Nicholas,
Hopefully this is fixed in version 1.52 which has just been released.
