### ISSUE TITLE
trying to download personal progress of OAS NOT WORKING

### ISSUE THREAD

**Issue by AkelaSue** [NomisNostab/Topo-Blazor#144]
trying to download personal progress of OAS in both Excel and in PDF comes up as corrupt file in excel or blank page in pdf,

![excel prob 2 on trying to open OAS  Core  2024-05-08 145257](https://github.com/NomisNostab/Topo-Blazor/assets/169230255/5f75c9b8-9fec-4203-8c96-f405593458f1)

![excel prob 1 on trying to open OAS CORE 2024-05-08 145138](https://github.com/NomisNostab/Topo-Blazor/assets/169230255/58e6f010-a301-4474-96c3-df4035a4c19e)

Theses are a copy of what I get back.

**Comment by AkelaSue** [comment]
hmm thought that i did do that.... sigh will do again shortly


Yours in Scouting,

Sue Day
'AKELA'
Cub Scout Leader
Publicity Officer
Grafton Scout Group
***@***.***
0401574697

[cid:d7fa9413-4964-4c2f-8726-f201b29015bb]
As Scouts of Australia, we acknowledge Australia’s First Nations Peoples, the Aboriginal and Torres Strait Islander peoples, as the Traditional Custodians of this land. We pay our respects to Elders past, present, and emerging. We’re grateful to do our Scouting in this country; we commit to use its resources wisely, and develop our understanding of Aboriginal and Torres Strait Islander cultures. We also acknowledge any Aboriginal and Torres Strait Islander Scouts who are part of our movement today.
________________________________

**Comment by AkelaSue** [comment]
attached file for you


Yours in Scouting,

Sue Day
'AKELA'
Cub Scout Leader
Publicity Officer
Grafton Scout Group
***@***.***
0401574697

[cid:bfb77882-43fd-4e70-8dd4-44561f2c5a3c]
As Scouts of Australia, we acknowledge Australia’s First Nations Peoples, the Aboriginal and Torres Strait Islander peoples, as the Traditional Custodians of this land. We pay our respects to Elders past, present, and emerging. We’re grateful to do our Scouting in this country; we commit to use its resources wisely, and develop our understanding of Aboriginal and Torres Strait Islander cultures. We also acknowledge any Aboriginal and Torres Strait Islander Scouts who are part of our movement today.
________________________________

**Comment by NomisNostab** [comment]
Hi Sue,
This isn't working, no attachments.
Send me a PM on messenger and I will give you my scouts email address and you can send it to me that way.

**Comment by AkelaSue** [comment]
Ok will do when I get home. Might be a few hours as doing a trip to Murwillumbah

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AkelaSue** [comment]
attachment is here, it was telling me that it was attached before as well but resending it... will find you on fb messenger as well



Yours in Scouting,

Sue Day
'AKELA'
Cub Scout Leader
Publicity Officer
Grafton Scout Group
***@***.***
0401574697

[cid:93f4ae51-01b4-425e-9404-d1e9a50f8ad7]
As Scouts of Australia, we acknowledge Australia’s First Nations Peoples, the Aboriginal and Torres Strait Islander peoples, as the Traditional Custodians of this land. We pay our respects to Elders past, present, and emerging. We’re grateful to do our Scouting in this country; we commit to use its resources wisely, and develop our understanding of Aboriginal and Torres Strait Islander cultures. We also acknowledge any Aboriginal and Torres Strait Islander Scouts who are part of our movement today.
________________________________

**Comment by NomisNostab** [comment]
The report was empty because there were no in-progress OAS stages.
I will make a change to disable the report button if there are no reports to produce.

**Comment by AkelaSue** [comment]
Ok. Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
