### ISSUE TITLE
Feature Request: Show event status in program

### ISSUE THREAD

**Issue by nick-pike** [NomisNostab/Topo-Blazor#145]
Would it be possible to add a column to the Program list showing the status of the event?  eg Planned vs Concluded.

This would make it easy to see if there's any program entries that haven't been concluded, even if the leader isn't listed as an organiser.

It looks like the status is available in the events.terrain/members/{id}/events api response.

I've mocked up what it could potentially look like;

![image](https://github.com/NomisNostab/Topo-Blazor/assets/6993122/8914c52b-1644-40fc-816d-353e971f0606)

Yours in Scouting,
Nick

**Comment by NomisNostab** [comment]
@nick-pike 
I can look into this for you.

**Comment by NomisNostab** [comment]
@nick-pike 
This has been added in version 1.54 which is being deployed now.
