### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by Chez67** [NomisNostab/Topo-Blazor#151]
Hi I am a member of 2 groups
Plantagenet Scouts original group ---wont load report
new added appointment Denmark Scouts
I am unable to now access my reports for Plantagenet Scout group comes up with an error but can access Denmark
my member number is 84923

![image](https://github.com/NomisNostab/Topo-Blazor/assets/170505816/d0b33f52-2f1e-447e-9747-364443cd56b1)

**Comment by Chez67** [comment]
I can navigate between the groups just  wont load reports for plantagenet

**Comment by NomisNostab** [comment]
Hi Cheryle,
It sounds like a permissions issue with Plantagenet group. You may have been removed as an adult member.
To help me check, can you follow the Debug Info instructions. I'll just need you to log logging on, selecting Plantagenet and going to the Members page.

PM me on the facebook group for my email address to send the logs.
Simon

**Comment by NomisNostab** [comment]
Hi Cheryle,
Thanks for the log file.
I have found the problem and v1.55 has been published that should fix things for you.
Simon.

**Comment by Chez67** [comment]
Thanks

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
