### ISSUE TITLE
Suppressing surnames for reports

### ISSUE THREAD

**Issue by mlhuppatz** [NomisNostab/Topo-Blazor#177]
Hello - this is a suggestion not an issue.

Would love to print out reports that don't show the full surname of our youth members - we rent out our hall to community groups and so need to be careful about what we put up on the pinboards.

Having said that our youth love to see their progress and so am wondering if there was a way to di-identify the reports slightly. The suggestion of first initial of surname would work in the vast majority of instances.

**Comment by NomisNostab** [comment]
Hi,
Which reports are you most likely to put up?
Simon

**Comment by mlhuppatz** [comment]
Hi Simon,

Thanks for following up on this - the #1 report that I would post up in the hall is the Wallchart.  Such an awesome report and gives the whole picture.

I do share the OAS reports with the kids but they don't have to go on wall as much - we could just show them on the night.

Cheers, ML


________________________________
