### ISSUE TITLE
Approvals screen: Request type "Review" for SIAs - please add Name and Focus fields when you go to the View screen

### ISSUE THREAD

**Issue by NukemNewbs** [NomisNostab/Topo-Blazor#179]
When using the Approvals screen and the Achievement Pathway is any "SIA" and the Request Type is "Review": when you click the "View" hyperlink, the resulting screen shows only the Review questions and answers of the SIA but does not show the "Name" and "Focus" fields  for the SIA. 

This makes it almost impossible to know what the youth was doing for the SIA for when doing the Review.

As a starting point could we please have the "Name" and "Focus" fields added for the SIA?

If it is possible when doing this change, it would be great to have all the fields for the SIA on the screen, but this is not as important as having the Name and Focus fields.

![Approval request not yet approved](https://github.com/user-attachments/assets/c6e92995-5b0e-4254-88ab-1f7bb744d857)

**Comment by NukemNewbs** [comment]
I just saw that the screen we need here is already in the system in the youth Basecamp > Special Interest Areas > Awarded section > click the View hyperlink on an SIA that has been awarded and you get the whole SIA screen including name, Goals, How, and Who headings.

That screen could be improved by adding in a "Review" title above the review questions and answers that are there.

**Comment by NomisNostab** [comment]
Hi,
I believe you are raising an issue regarding Terrain, not Topo. I don't do anything with Terrain, follow the support/help info in Terrain.

Simon.

**Comment by NukemNewbs** [comment]
Darn Simon,

You are exactly right.  I thought that i'd tapped straight into the
developers for Terrain via GitHub!  Bummer, and thanks for letting me
know.  Please delete my requests.

Cheers,
Andrew

**Comment by NukemNewbs** [comment]
Sorry Simon, please delete these 3 request as you are right, they are for Terrain. :P

**Comment by NomisNostab** [comment]
Closed as these are Terrain issues
