### ISSUE TITLE
Approvals screen: Request type "Award" for SIAs - please add Name and Focus fields when you go to the View screen

### ISSUE THREAD

**Issue by NukemNewbs** [NomisNostab/Topo-Blazor#180]
When using the Approvals screen and the Achievement Pathway is any "SIA" and the Request Type is "Award": when you click the "View" hyperlink, the resulting screen shows only the Review questions and answers of the SIA but does not show the "Name" and "Focus" fields for the SIA.

This makes it almost impossible to know what the youth was doing for the SIA for when preparing to award the badge.

As a starting point could we please have the "Name" and "Focus" fields added for the SIA?

If it is possible when doing this change, it would be great to have all the fields for the SIA on the screen, but this is not as important as having the Name and Focus fields.

**Comment by NukemNewbs** [comment]
I just saw that the screen we need here is already in the system in the youth Basecamp > Special Interest Areas > Awarded section > click the View hyperlink on an SIA that has been awarded and you get the whole SIA screen including name, Goals, How, and Who headings.

That screen could be improved by adding in a "Review" **title** above the review questions and answers that are there.

**Comment by NomisNostab** [comment]
Closed as these are Terrain issues
