### ISSUE TITLE
Basecamp (for youth) > Special Interest Areas > Review section: clicking View hyperlink on an SIA that is "Pending review" does not show full SIA information

### ISSUE THREAD

**Issue by NukemNewbs** [NomisNostab/Topo-Blazor#181]
When using Terrain as a youth member (or as a Leader using the Manage Achievement Pathways) when you go to the Special Interest Areas screen and look at SIAs needing your review you click on the View hyperlink for a particular SIA that is "Pending review" and the resulting screen does not show the full information for that SIA, just the review questions.

This means the youth member cannot see what they planned to do for this SIA, just the title in the previous SIA screen and the review questions in this screen.

It would be great your the youth to be able to see what they said they would do for the SIA in this screen as well as the review questions and answers for the SIA.

**Comment by NomisNostab** [comment]
Closed as these are Terrain issues
