### ISSUE TITLE
Topo Approvals Report is showing multiple rows

### ISSUE THREAD

**Issue by MrOsito** [NomisNostab/Topo-Blazor#190]
This could be user error so apologies upfront if that is the case.

We went through our first round of badge presentation this week and found that the Topo report, in many cases, displayed two rows for youth.

The key difference was that Type was Review and Award.

My expectation is that you would see only one row.

![image](https://github.com/user-attachments/assets/2691d098-ec6a-41f9-b7c5-396021651318)

**Comment by NomisNostab** [comment]
Hi,
I am aware of this and am working on a fix.
It is due to the new Award step to record when a member has been awarded/presented the badge.
The Review is for when a member submits an achievement for review by the unit council.
Simon.

**Comment by NomisNostab** [comment]
Fixed in v1.62
