### ISSUE TITLE
ALL Leads and Assists for a YM - whether accumulated on a Milestone or not

### ISSUE THREAD

**Issue by Segopsed** [NomisNostab/Topo-Blazor#191]
Hi Simon,

Is there any way of pulling data from Terrain that shows all the Leads and Assists a Youth Member has accrued, even if they have already completed the Lead or Assist requirement for a Milestone?

I have some youth members whom I am reasonably sure have done more Leads or Assists than is reflected in their Milestone progress. However, because they have not completed Participates for that Milestone, their 'extra' Leads and Assists are not credited anywhere (the extra L/As don't count as Ps for that Milestone, either). Currently, the only way of collecting that data is to go into each program item and count them manually. 

I am the lone leader for my unit of Cub Scouts. They and their parents don't always know where they are up to and I am often too overwhelmed to properly keep track and thus prevent them accruing too many L/As. Having a report to count them for me would be a boon! Of course, a report that shows the date, challenge area and name of the program item would be great too, but even just a count would make a big difference to me. A bonus alternative report would be having the count for all the youth members on one page.

Appreciate this may not be possible, and even if so, not a high priority for a volunteer developer.

Yis, Simone (Scouts NSW)

**Comment by NomisNostab** [comment]
Hi Simone,

Have a look at the Personal Progress report for the Cub.
It will so every PAL event that has contributed to their milestones, as long as it was recorded in Terrain.

There is also the Attendance report available from the Program page.
Put a date range in for a term and run the Attendance Report at the bottom of the page.

Let me know how you go.

Simon.

**Comment by Segopsed** [comment]
> Hi Simone,
> 
> Have a look at the Personal Progress report for the Cub. It will so every PAL event that has contributed to their milestones, as long as it was recorded in Terrain.
> 
> There is also the Attendance report available from the Program page. Put a date range in for a term and run the Attendance Report at the bottom of the page.
> 
> Let me know how you go.
> 
> Simon.

Hi Simon,

I did look at the PP Report, but it didn't show what I thought I would see. It is possible it's GIGO though.

With regards to the Attendance Report, it doesn't seem to appear for me:
![Screenshot 2024-10-14 140107](https://github.com/user-attachments/assets/9d3aeca8-6fae-4376-91ca-3cc1ee9d0a81)

**Comment by Segopsed** [comment]
Deleted previous comment re. attendance because I realised I'd entered a range with no attendance. Silly me.

**Comment by NomisNostab** [comment]
Hi Simone,

I am closing this as I think it was resolved.

Simon.
