### ISSUE TITLE
OAS Report Generation - unhandled error

### ISSUE THREAD

**Issue by hartnickaus** [NomisNostab/Topo-Blazor#2]
Steps to reporduce.
Select a Unit - 
Selected 1 or more Stages
Click either "OAS Worksheet (pdf)" or  "OAS Worksheet (xlsx)" and error appears at bootom of screen.

Note: if i "Hide completed members" is checked then either report works as expected

![image](https://user-images.githubusercontent.com/30915527/187806122-d6385156-10a0-4ada-8bf9-2aed5b8520c9.png)

**Comment by NomisNostab** [comment]
Fixed processing empty date fields
