### ISSUE TITLE
An unhandled error has occurred. Reload

### ISSUE THREAD

**Issue by chriswsa** [NomisNostab/Topo-Blazor#39]
Receiving this currently on every page when using  https://nomisnostab.github.io/Topo-Blazor/#

**Comment by NomisNostab** [comment]
Ok.
If you have not yet done so, click Reload and see if that solves the problem.
Next force reload the app with Ctrl+F5 (Cmd+F5 for Mac I think).

Let me know how you go.

**Comment by chriswsa** [comment]
Problem may be solved - tried a different account and it worked fine. My account has higher privileges across multiple groups so it wasn't loading the units properly it seems!

**Comment by NomisNostab** [comment]
Hi Chris,
Yes that is correct, someone else has just reported a similar problem when they belong to more than one group.
I'll get a fix out for this.

**Comment by NomisNostab** [comment]
Fixed in v1.36

**Comment by chriswsa** [comment]
Thanks! Great work!
