### ISSUE TITLE
Enhancement to Programs report

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo-Blazor#41]
Add additional columns to the Programs report:

- Start date/time
- End date/time
- Organiser name
- Lead/Assist name
- Location

**Comment by NomisNostab** [comment]
@acsand 
Did you want these columns to show on the Program page? Real estate is a bit tight.
I have added the following
![image](https://user-images.githubusercontent.com/65288066/231445363-c36a092f-cafd-43a9-981f-96afced5e460.png)

They will all be in the "Term Program" report

**Comment by acsand** [comment]
@NomisNostab That looks good. I know real estate is tight, but could we get an "Assist" column in as well? Perhaps wrap the "Program Name" and "Location" columns?

**Comment by NomisNostab** [comment]
@acsand 
New look with combined Program and Location
![image](https://user-images.githubusercontent.com/65288066/232426729-aaf0a150-6701-4197-9014-481e212f1d99.png)

**Comment by acsand** [comment]
@NomisNostab Looks good. So long as we can export to excel, we can do further manipulation to 'dress it up' for distribution to members.

**Comment by NomisNostab** [comment]
Included in v1.40
