### ISSUE TITLE
Export Programs report calendar view

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo-Blazor#42]
Ability to export the tabular calendar view to excel format to allow creation of a program for distribution to youth/leaders/parents

**Comment by NomisNostab** [comment]
@acsand 
Attached is the current export to excel of the term program, untouched.
[TermProgram_ToExcel.xlsx](https://github.com/NomisNostab/Topo-Blazor/files/11333050/TermProgram_ToExcel.xlsx)
I have based it off our term program layout where we use the Date and Start and Finish columns. 
I added the Start and End columns to the beginning to allow different formatting as these are date columns not text values.
We use Operoo for parent permission.
Is there anything I have missed?

**Comment by acsand** [comment]
Hey @NomisNostab has this feature been released to production? I just ran the Program report for the next term, and it's not producing a calendar view. Am I missing something?

**Comment by NomisNostab** [comment]
Hi Andrew,

Not yet, I plan to release it tonight.
Stay tuned :-)

Simon

***@***.***
0414 906 272

**Comment by acsand** [comment]
Awesome. Just in time for Term 2. :-)

**Comment by NomisNostab** [comment]
Slight delay, need to fix up time zones on report. Everything was set to UTC, as that is the time zone the report generator is running in.
