### ISSUE TITLE
Unhandled Error when downloading files

### ISSUE THREAD

**Issue by wilsteady** [NomisNostab/Topo-Blazor#45]
Keep getting an unhandled error warning each time I try to run any download reports. Error does not present earlier and allows me to view the sections I have access to in Terrain through the variety of drop down menus and on the approvals page. 

Currently using Microsoft Edge v108.0.1462.54

Excerpt from Dev Console below
`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No unit found with name GM Scouts (Grovely-Mitchelton Scout Group). You may not have permissions to this section
System.IndexOutOfRangeException: No unit found with name GM Scouts (Grovely-Mitchelton Scout Group). You may not have permissions to this section
   at Topo.Services.StorageService.get_Section()
   at Topo.Services.WallchartService.GetWallchartItems(String selectedUnitId)
   at Topo.Controller.WallchartController.WallchartReport(OutputType outputType)
   at Topo.Controller.WallchartController.WallchartReportPdfClick()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )`

**Comment by NomisNostab** [comment]
Hi Brendan,
The Terrain roles have changed recently and a few people are having similar issues.
Topo is not reading the new role structure correctly.
I presume you are using the Topo Blazor online version of Topo.
Can you Open the Dev console (F12),
Log in, run the wallchart report and save the complete console output to a file?
(Right click in the console message area and Save All messages to a file.
I will be able to see how the role structure has changed and fix it.
Simon.

**Comment by wilsteady** [comment]
Hi Simon, Console Log attached. 
My primary appointment is a District Leader and all sections I have access to I was manually added to. QLD has not yet implemented the Support Leader access properly. 

[nomisnostab.github.io-1673164598326.log](https://github.com/NomisNostab/Topo-Blazor/files/10367939/nomisnostab.github.io-1673164598326.log)

**Comment by NomisNostab** [comment]
Thanks Brendan,
The log shows me what I need.

**Comment by NomisNostab** [comment]
Hi Brendan,
Can I get you to Log in, go to the Program page and then send me the console log?
I need to see how the calendars are returned when you belong to many groups and units.
Thanks

Simon

**Comment by wilsteady** [comment]
No dramas - See attached. 
[Program-GMScouts-01Jan2022to08May2023.log](https://github.com/NomisNostab/Topo-Blazor/files/10368242/Program-GMScouts-01Jan2022to08May2023.log)

**Comment by NomisNostab** [comment]
Hi Brendan,
I have made some changes that will hopefully fix your issues.
Once you have logged in and are on the Home page, you will have to select a group to view.
You can go back to the home page and change groups at any time.
Please try it out.

**Comment by wilsteady** [comment]
Hi Simon, looks to be working so far. Can download the wall chart report successfully now too. 
Have just seen on the Facebook Group for Terrain that someone got caught out by the change. Would it work if there is only one group you’re linked to, to default to that one and only present a drop down box to choose if more than one group?

**Comment by NomisNostab** [comment]
Hi Brendan,
Thanks.
Yes it will work for us mere mortals that just belong to a single group.
It will select that group by default.
