### ISSUE TITLE
Incorrect OAS progress reporting in Personal Progression report

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo-Blazor#66]
Currently, the OAS section of the Personal Progression reports the _lowest_ stage that is currently in progress. This presents a problem for OAS areas where there are multiple streams, as it appears a youth member is working at a lower stage than is actually the case.

The classic example is Bushcraft, which has the Survival and Pioneering streams. If a Scout has Survival 4 complete, but has Pioneering 4 in progress, it appears in the Personal Progress report as if they need two more progressions to reach the Bushcraft 5 requirement for the peak award, when in fact they only need one (Survival 5).

My suggestion would be to report the highest stage completed in any stream of an OAS area, or alternatively explicitly report on each stream within an OAS area.

**Comment by NomisNostab** [comment]
Fixed in v1.42.
Selects the most recently completed OAS stage
