### ISSUE TITLE
Program report not running

### ISSUE THREAD

**Issue by acsand** [NomisNostab/Topo-Blazor#74]
Since releasing v1.40 of Topo, the Program report isn't working. I select my unit, two dates (1/5 to 30/6), Include Group events, and show Unit Calendar. The wheel spins for a while, but no calendar appears.

**Comment by NomisNostab** [comment]
Andrew,
Can you run this with the F12 console showing and send me the console log.
I suspect it might be the support roles you have.

**Comment by NomisNostab** [comment]
@CrispyCamper @acsand 
Can you run this with the F12 console showing and send me the console log.
Start Topo, but don't login.
F12 to show console.
Login, go to Program page, fill out details to get error.
The F12 console should have a log of the data from Terrain and any errors.
Right click on console and save as, email to me.

**Comment by NomisNostab** [comment]
@CrispyCamper @acsand 
This should be resolved by v1.41 just published.
