### ISSUE TITLE
Enhancement - AJ2025 Eligibility Report

### ISSUE THREAD

**Issue by wilsteady** [NomisNostab/Topo-Blazor#90]
To help support leaders in the run up to AJ2025, a simple report in A4 Portrait, similar to the Wall Chart Report, that simply outputs a youth's progression against the AJ25 eligibility criteria. [Webpage](https://aj2025.com.au/participant-eligibility-requirements/)

Image for reference of idea. Fake details entered. Not sure if it's possible to calculate nights under canvas from logbook based on the section they were in at the time of earning? 
![image](https://github.com/NomisNostab/Topo-Blazor/assets/12633684/53aa4cf9-351e-430b-88c2-a42be888b410)

**Comment by NomisNostab** [comment]
Hi,
Have you had a look at the progress report for a scout? All that info is there for a scout.
Simon.

**Comment by NomisNostab** [comment]
Hi Brendan,
Going to be tough though for nights camped in scout unit.
Terrain doesn't have a date for when a scout joined the section, the best I can use is Intro to Section awarded date.
Logbook entries only have a start and end date, no section info.
I can do it for kids with an Intro to Section awarded, hard without one though.
Simon.
