### ISSUE TITLE
Individual OAS Report Failing - An unhandled error has occurred.

### ISSUE THREAD

**Issue by AceLeader2023** [NomisNostab/Topo-Blazor#98]
Having issue using the latest feature in the Personal Progress area, I am not able to get the OAS Report nor the Core OAS Report. 

The outcome after clicking and waiting is a banner comes up at the bottom of screen saying "an unhandled error has occurred".

**Comment by NomisNostab** [comment]
Hi,

I'm overseas at the moment, will look into it when I get home.
Try a Ctrl + F5 to reload the Topo app and see if that helps.

Simon

***@***.***
0414 906 272

**Comment by NomisNostab** [comment]
Also,
Try a normal OAS report

**Comment by AceLeader2023** [comment]
Yes, a normal OAS report from OAS area works fine, it is just OAS reports
in individual progression area that does not work.

**Comment by NomisNostab** [comment]
Hi,

I wonder if there is some bad data?
In Topo, go to Personal progress for the unit.
Press F12 to show the Developer Tools. Click on the console tab. Clear the
console using the circle with a slash.
Click on the Progress link to show the details and then the report button.
Right click anywhere in the console area and select save as.
Save the log and email to me. I see if anything looks wrong. It might give
me more info on what is causing the error.

[image: image.png]
Simon

***@***.***
0414 906 272

**Comment by NomisNostab** [comment]
Increased memory allocation and timeout value.
